### ISSUE TITLE
reproducing results for "crypto-js" library

### ISSUE THREAD

**Issue by canertol** [microwalk-project/Microwalk#12]
Hi,

I want to reproduce results for [crypto-js](https://github.com/brix/crypto-js) library but I couldn't figure out the right configuration used in the paper.
In the _develop_ branch, there is no index.js given, so I tried testing the _master_ branch. I get the following error:
```Running target target-example...
Failed to instrument ;(function (root, factory) {
..............
<content of crypto-js.js here.>
..............
analysis exception!!!
TypeError: ExprGen[$param.type] is not a function
    at generateFunctionParams (/mw/jalangi2/node_modules/esotope/esotope.js:684:45)
    at generateFunctionBody (/mw/jalangi2/node_modules/esotope/esotope.js:705:9)
    at Object.generateFunctionExpression [as FunctionExpression] (/mw/jalangi2/node_modules/esotope/esotope.js:1180:13)
    at Object.generateCallExpression [as CallExpression] (/mw/jalangi2/node_modules/esotope/esotope.js:1004:35)
    at Object.generateProperty [as Property] (/mw/jalangi2/node_modules/esotope/esotope.js:1261:39)
    at Object.generateObjectExpression [as ObjectExpression] (/mw/jalangi2/node_modules/esotope/esotope.js:1281:38)
    at Object.generateCallExpression [as CallExpression] (/mw/jalangi2/node_modules/esotope/esotope.js:1004:35)
    at Object.generateCallExpression [as CallExpression] (/mw/jalangi2/node_modules/esotope/esotope.js:1004:35)
    at Object.generateCallExpression [as CallExpression] (/mw/jalangi2/node_modules/esotope/esotope.js:1004:35)
    at Object.generateCallExpression [as CallExpression] (/mw/jalangi2/node_modules/esotope/esotope.js:1004:35)
```

The content of the target-example.js is the following. I wanted to keep it simple to make sure the problem is not in my code.

```
  // Executes the given testcase.
  // Parameters:
  // - testcaseBuffer: Buffer object containing the bytes read from the testcase file.
  function processTestcase(testcaseBuffer)
  {
        var testcase = testcaseBuffer.toString();
        /* TODO */
  }
  module.exports = { processTestcase };
```

**Comment by JanWichelmann** [comment]
Hi!

Looks like the issue is with the crypto-js library and Jalangi2's parser. Jalangi2 is a bit limited in terms of supported syntax, leading to weird errors like this. We are working on a replacement that will also support recent JS versions, but that may still take a while.

For our analysis we pulled the NPM package, and used it as following:
```js
var CryptoJS = require('crypto-js');

function processTestcase(testcaseBuffer)
{
    var message = CryptoJS.lib.WordArray.create(new Uint8Array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]));
    var key = CryptoJS.lib.WordArray.create(new Uint8Array(testcaseBuffer));
	
    var ciphertext = CryptoJS.AES.encrypt(message, key, { mode: CryptoJS.mode.ECB, padding: CryptoJS.pad.NoPadding });

    //console.log("", CryptoJS.enc.Hex.stringify(ciphertext.ciphertext));
}

module.exports = { processTestcase };
```

If this still doesn't work, please let me know, then I will send you our entire source tree for the crypto-js target (including initialized node_modules etc.).

**Comment by canertol** [comment]
Thanks for the quick reply.
I have tried replacing the example Javascript template with the one you provided. It gave the same error.

**Comment by JanWichelmann** [comment]
I've sent you the source tree via email.

We ran our analysis on the NPM version of crypto-js, which was compatible with Jalangi2.
